import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB" className="dark" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased h-[100dvh]`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <QueryProvider>
            <Header/>
            <main className="h-full overflow-y-auto flex justify-center items-center">
              {children}
            </main>
            <Footer></Footer>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
